name: Deploy on server.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t ya-workshop-registration-service .

      - name: Save Docker Image to File
        run: |
          docker save ya-workshop-registration-service -o ya-workshop-registration-service.tar
          chmod 644 ya-workshop-registration-service.tar

      - name: Transfer Docker image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "ya-workshop-registration-service.tar,docker-compose.yml"
          target: ~/deploy/registration-service/

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/deploy/registration-service/
            docker load -i ya-workshop-registration-service.tar
            docker compose down
            docker compose up -d